### ISSUE TITLE
Rubocop load Psych:Module error

### ISSUE THREAD

**Issue by stardiviner** [bbatsov/rubocop#2178] opened 2015-08-24 00:06 UTC
``` 
⇨   rubocop test.rb                                                         
Inspecting 1 file


0 files inspected, no offenses detected
private method `load' called for Psych:Module
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/config_loader.rb:152:in `yaml_safe_load'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/config_loader.rb:138:in `load_yaml_configuration'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/config_loader.rb:27:in `load_file'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/config_loader.rb:85:in `configuration_from_file'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/config_store.rb:40:in `for'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:133:in `inspect_file'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:106:in `block in do_inspection_loop'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:100:in `loop'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:100:in `do_inspection_loop'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:78:in `process_file'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:53:in `block in inspect_files'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:51:in `each'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:51:in `inspect_files'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:30:in `run'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/lib/rubocop/cli.rb:26:in `run'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/bin/rubocop:13:in `block in <top (required)>'
/home/stardiviner/.rbenv/versions/2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/home/stardiviner/.gem/ruby/2.2.0/gems/rubocop-0.33.0/bin/rubocop:12:in `<top (required)>'
/home/stardiviner/.gem/ruby/2.2.0/bin/rubocop:23:in `load'
/home/stardiviner/.gem/ruby/2.2.0/bin/rubocop:23:in `<main>'

stardiviner [ ~/Code/learning/Ruby ] § Ruby: {2.2.0}
-----------
```

**Comment by bquorning** [comment] 2015-08-24 07:17
Duplicate of #1510. In short:

> this is [a rubygems bug](https://github.com/rubygems/rubygems/commit/5bb291fc31d16e527b4d0a1a4f64aa32f27f5255). `gem update --system` will help you.

**Comment by stardiviner** [comment] 2015-08-24 07:52
@bquorning Thanks

**Closed** 2015-08-24 07:51 UTC

**Comment by bbatsov** [comment] 2015-08-24 08:41
Recurring issues like this one make me start wondering if adding a troubleshooting section to the readme won't be helpful. Of course, having it there doesn't mean someone will actually read it.

**Comment by stardiviner** [comment] 2015-08-24 10:57
I guess that's because people think it's README, not FAQ, usually I read it when I install it, then I forget what it said. That's true, not many people will remember that I guess. Add a link in README to Git Wiki page "FAQ" is enough. Usually my flow is 1: Google, 2: find project, 3: search or ask. And sometimes, I think this is something wrong, I skip previous steps.
