### ISSUE TITLE
Error is thrown while running rubocop with -a flag on code with nested hash

### ISSUE THREAD

**Issue by michniewicz** [bbatsov/rubocop#4803] opened 2017-09-27 08:50 UTC
## Expected behavior

execution with autocorrection should not fail

## Actual behavior

running rubocop command with auto-correct option throws an error on code with nested hash

```
undefined method `begin' for nil:NilClass
```

## Steps to reproduce the problem

Sample code to test the issue:

filename: `test.rb`

```
class Test
  def foo
    params[:foo] && params[:foo][:bar]
  end
end
```

executing `rubocop test.rb` prints out offence:

```
test.rb:5:5: C: Use safe navigation (&.) instead of checking if an object exists before calling the method.
    params[:foo] && params[:foo][:bar]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

but executing `rubocop -a test.rb` throws an error.

## RuboCop version

```
$ rubocop -V
0.50.0 (using Parser 2.4.0.0, running on ruby 2.4.2 x86_64-linux)
```

**Comment by Drenmi** [comment] 2017-09-27 13:43
Duplicate of #4731, #4741, #4760, #4766, and #4771. 😅  Fixed in #4749. Bugfix release coming soon.

**Closed by Drenmi** 2017-09-27 13:43 UTC
