### ISSUE TITLE
An error occurred while Performance/DoubleStartEndWith

### ISSUE THREAD

**Issue by wilg** [bbatsov/rubocop#4806] opened 2017-09-27 23:25 UTC
```
An error occurred while Performance/DoubleStartEndWith cop was inspecting [file].
name<method> after <receiver>
org/jruby/RubyString.java:1191:in `%'
org/jruby/RubyKernel.java:811:in `sprintf'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/performance/double_start_end_with.rb:71:in `add_offense_for_double_call'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/performance/double_start_end_with.rb:39:in `on_or'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/commissioner.rb:44:in `block in on_or'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/commissioner.rb:109:in `with_cop_error_handling'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/commissioner.rb:43:in `block in on_or'
org/jruby/RubyArray.java:1734:in `each'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/commissioner.rb:42:in `on_or'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/ast/traversal.rb:128:in `on_if'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/commissioner.rb:48:in `on_if'
(eval):2:in `block in on_begin'
org/jruby/RubyArray.java:1734:in `each'
(eval):2:in `on_begin'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/commissioner.rb:48:in `on_begin'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/ast/traversal.rb:154:in `on_block'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/commissioner.rb:48:in `on_block'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/ast/traversal.rb:154:in `on_block'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/commissioner.rb:48:in `on_block'
(eval):2:in `block in on_begin'
org/jruby/RubyArray.java:1734:in `each'
(eval):2:in `on_begin'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/commissioner.rb:48:in `on_begin'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/ast/traversal.rb:88:in `on_class'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/commissioner.rb:48:in `on_class'
(eval):2:in `block in on_begin'
org/jruby/RubyArray.java:1734:in `each'
(eval):2:in `on_begin'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/commissioner.rb:48:in `on_begin'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/ast/traversal.rb:12:in `walk'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/commissioner.rb:60:in `investigate'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/team.rb:114:in `investigate'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/team.rb:102:in `offenses'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/runner.rb:258:in `inspect_file'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/runner.rb:205:in `block in do_inspection_loop'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/runner.rb:237:in `block in iterate_until_no_changes'
org/jruby/RubyKernel.java:1298:in `loop'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/runner.rb:230:in `iterate_until_no_changes'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/runner.rb:201:in `do_inspection_loop'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/runner.rb:111:in `block in file_offenses'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/runner.rb:121:in `file_offense_cache'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/runner.rb:109:in `file_offenses'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/runner.rb:100:in `process_file'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
org/jruby/RubyArray.java:1734:in `each'
org/jruby/RubyEnumerable.java:936:in `inject'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/runner.rb:75:in `each_inspected_file'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/runner.rb:67:in `inspect_files'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/runner.rb:39:in `run'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cli.rb:86:in `execute_runner'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/lib/rubocop/cli.rb:32:in `run'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/bin/rubocop:13:in `block in (root)'
/Users/wil/.rvm/rubies/jruby-9.1.8.0/lib/ruby/stdlib/benchmark.rb:308:in `realtime'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bundler/gems/rubocop-0d3b75280234/bin/rubocop:12:in `<main>'
org/jruby/RubyKernel.java:979:in `load'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bin/rubocop:1:in `<eval>'
org/jruby/RubyKernel.java:1000:in `eval'
/Users/wil/.rvm/gems/jruby-9.1.8.0@looker/bin/jruby_executable_hooks:15:in `<main>'
```
--------

## Expected behavior

Lint the file.

## Actual behavior

Crash asking for issue report.

## Steps to reproduce the problem

Looking into this...

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.50.0 (using Parser 2.4.0.0, running on jruby 2.3.1 java)
```

Gemfile.lock:
```
GIT
  remote: git@github.com:bbatsov/rubocop.git
  revision: 0d3b752802340a60b81adcacf144724d6c07b463
  specs:
    rubocop (0.50.0)
      parallel (~> 1.10)
      parser (>= 2.3.3.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 2.2.2, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
```

**Comment by pocke** [comment] 2017-09-28 01:21
Please give me code to reproduce.


Maybe this problem is related to https://github.com/bbatsov/rubocop/issues/4686

**Comment by pocke** [comment] 2017-11-25 15:02
I'll close this issue, because it's duplicated probably. If you still have this problem with latest JRuby, please reopen the issue or open a new issue.

**Closed by pocke** 2017-11-25 15:02 UTC
Labels: bug, duplicate
