### ISSUE TITLE
Style/CommentedKeyword false positive

### ISSUE THREAD

**Issue by jcoyne** [bbatsov/rubocop#5161] opened 2017-11-29 01:10 UTC
```
app/models/vocab/fedora_resource_status.rb:3:105: C: Style/CommentedKeyword: Do not place comments on the same line as the class keyword.
  class FedoraResourceStatus < RDF::StrictVocabulary('http://fedora.info/definitions/1/0/access/ObjState#')
                                                                                                        ^^^
```

In rubocop 0.51.0

**Comment by michniewicz** [comment] 2017-11-29 12:45
I believe this is fixed by https://github.com/bbatsov/rubocop/pull/4944 in master branch

**Comment by Drenmi** [comment] 2017-11-29 12:58
Duplicate of #4886. Fixed in #4944.

**Closed by Drenmi** 2017-11-29 12:58 UTC
Labels: bug, duplicate
