### ISSUE TITLE
Inline directive settings

### ISSUE THREAD

**Issue by zverok** [bbatsov/rubocop#5736] opened 2018-03-30 08:26 UTC
One pattern I've seen several times in different codebases is:

```ruby
def some_algorithmically_compex_method # rubocop:disable Metrics/AbcSize -- 15.17/15
```

That (if some method is _a bit_ more complex than the current threshold) may be reasonable, but then it can become an excuse to blow the method up to Abc 500 without noticing. 

I believe it could be some reasonable syntax to do this instead:

```ruby
def some_algoritmically_complex_method # rubocop:set Metrics/AbcSize(Max: 17)
```

...and have Rubocop complaining about this particular method after the new threshold reached.

**Comment by Drenmi** [comment] 2018-03-30 11:51
Duplicate of #2716.

**Closed by Drenmi** 2018-03-30 11:51 UTC
Labels: duplicate, feature request
