### ISSUE TITLE
"Unnecessary <xyz> encoding comment." - is the check correct for Encoding in use in a .rb file?

### ISSUE THREAD

**Issue by shevegen** [bbatsov/rubocop#4784] opened 2017-09-23 22:35 UTC
Hello rubocop dev team,

Before I describe my issue (or rather, the behaviour I noticed), here my system:

Linux 64 bit / ruby version: 2.4.2p198 / rubocop version: 0.5.0 (using Parser 2.4.0.0), gem version 2.6.13.

The issue or behaviour I find happens with e. g. a minimal example such as this one here:

    #!/usr/bin/ruby -w
    # Encoding: ISO-8859-1
    puts 'hi there'

Rubocop says:

    foo.rb:2:1: C: Unnecessary utf-8 encoding comment.
    # Encoding: ISO-8859-1
    ^^^^^^^^^^^^^^^^^^^^^^

I do not know if this behaviour is wanted or not, so I can not really recommend any way
to resolve it IF it is not wanted. To clarify, the encoding that I use is not utf-8, so to me it
is a bit strange that rubocop assumes it to be utf-8. Most people probably use utf-8 
anyway, so I really don't know if rubocop should report anything else - I just thought 
that it is best to report it in the event that the code only assumes utf-8 encoding even
though another encoding may be used such as iso-8859-1 (not sure if the upcased
variant influences rubocop; the above encoding comment seems to work for ruby 
files).

The expected behaviour I would think would be that rubocop should not assume it
to be an unnecessary encoding comment if it is NOT a utf-8 file (or at the least 
the encoding says that it is something different).

Thanks for reading, please do feel free to close this at any moment in time - rubocop's
autocorrect feature is awesome!

**Comment by Drenmi** [comment] 2017-09-24 09:20
Looks like a duplicate of #4776 (bug). Closing this. Feel free to follow the other issue for updates. 🙂

**Closed by Drenmi** 2017-09-24 09:20 UTC
