### ISSUE TITLE
Rubocop --auto-correct is very slow 

### ISSUE THREAD

**Issue by stereobooster** [bbatsov/rubocop#2047] opened 2015-07-17 13:55 UTC
It seems that autocorrect writes out file to disk after every offence fix. Which is very slow. Started rubocop and opened file in sublime the same time and can see how it is replacing tabs with space one line at time. Didn't dig in source yet, so it is just an assumption. Any reason why we cannot write out file after it all was fixed or at least by bigger chunks then one line?
```
rubocop -v 0.32.1
```

**Comment by jonas054** [comment] 2015-07-21 02:16
I think it should be possible to just make changes to a buffer object in memory and write to disk when all changes are done. Worth investigating.

**Comment by alexdowad** [comment] 2016-01-07 19:37
> It seems that autocorrect writes out file to disk after every offence fix. Which is very slow.

You're right that autocorrect is way, way, way too slow. But it's unlikely that saving the file after each fix has anything to do with it. To understand why, you need to know something about how operating systems work.

Your OS uses much of your computer's memory to cache pages from files. When you save some data into a file, the OS merely updates one or more cached pages and marks them as dirty. Whenever it is ready to do so, it writes the dirty pages out to disk and then marks them as clean. This is asynchronous and happens in the background.

While those dirty pages are sitting in memory, waiting to be written out, you can keep updating the file, perhaps 100s of times, and everything will just be happening in memory.

So the problem is really `File.open('name', 'w') { ... }`, that would indicate some inefficiency in Ruby's implementation of I/O, rather than an inherent problem with repeatedly saving a file.

The real problem, which you also alluded to, is the quadratic run time which results from repeating the entire inspection process after each fix. This is worst when the source code contains tabs -- when there are no tabs, all the fixes from a single cop are applied, then the inspection process starts over afresh. When there are tabs, just one fix from one cop is applied before starting everything over.

I'd like to see if there is some way to tame that fearsome O(n^2) behavior, but first, I am working on optimizing out various other inefficiencies to make the constant factor as small as possible.

Expect significant performance enhancements soon.

**Comment by alexdowad** [comment] 2016-01-21 08:20
Although a few optimizations made it into `0.36.0`, we are still far too slow. I tried autocorrecting Rails' `actionpack` -- it took 2 hours.

I have an optimization which cuts autocorrection time by about 1/3, but that's not enough. More work is needed to kill this bottleneck.

**Comment by jakeonrails** [comment] 2016-02-29 21:16
Is it really necessary to "autocorrect", or would it be possible to rewrite the entire file line by line, like what a beautifier would do? I believe Go actually has some sort of tool like gofmt or something that does this.

**Comment by alexdowad** [comment] 2016-03-08 18:34
> Is it really necessary to "autocorrect", or would it be possible to rewrite the entire file line by line, like what a beautifier would do?

This would be *very* effective in making coding style consistent, since each possible AST would have one, and only one, canonical textual representation.

It's not a bad idea, but it would be a completely different program from RuboCop.

Note that RC also does things like checking for unused variables and such, which is more than what a beautifier does.

**Comment by alexdowad** [comment] 2016-03-08 18:38
When my next PR is merged, autocorrection will no longer be slow. That "2 hours" to autocorrect Action Pack is now a minute and 30 seconds; not quite a 100x speedup. (19,521 offenses detected, 15,512 corrected!)

This issue can be closed.

**Comment by alexdowad** [comment] 2016-03-08 19:17
Got it down to about 1:20...

**Comment by jakeonrails** [comment] 2016-03-08 20:12
Like a boss! Super stoked - my gem depends on Rubocop for every Rails migration (fix-db-schema-conflicts). Running autocorrect against a 1500 line schema takes 31s. Getting that down to even 1/10 would be a huge win! Can you talk a bit about how you implemented your solution? Or should I just wait til the PR? :D

**Comment by alexdowad** [comment] 2016-03-09 03:52
@jakeonrails There were several cops which would check the validity of every autocorrection by reparsing the whole file. This is convenient, but terrible for performance, *especially* on large files.

**Comment by jonas054** [comment] 2016-03-13 13:21
Fantastic work, @alexdowad!

**Closed by jonas054** 2016-03-13 13:21 UTC
Labels: enhancement
