### ISSUE TITLE
Issue with Indentation cops when pushing to an Array

### ISSUE THREAD

**Issue by Gawyn** [bbatsov/rubocop#4346] opened 2017-05-04 22:14 UTC
The indentation cops seem to have an unconsistent behaviour in some cases. For example, the following script will find an indentation issue for pushing to an Array, but not for the assignment:

```
a = []

b = if a.empty?
  1
else
  2
end

a << if b != 2
  1
else
  2
end

p b
```

This returns:
```
Inspecting 1 file
W

Offenses:

foo.rb:10:3: C: Style/IndentationWidth: Use 2 (not -3) spaces for indentation.
  1 ...
  ^
foo.rb:11:1: C: Style/ElseAlignment: Align else with if.
else
^^^^
foo.rb:13:1: W: Lint/EndAlignment: end at 13, 0 is not aligned with if at 9, 5.
end
^^^
```

The `Lint/EndAlignment` cop is configured to align with `variable`.

## RuboCop version

```
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on jruby 2.3.1 java)
```

**Comment by Drenmi** [comment] 2017-05-05 03:58
Technically it is Ruby that is inconsistent, as `=` is an assignment, and `#<<` is a method send that will evaluate a suffixed multiline `if` condition (which is not true for most other methods.) 🙂 

That said, if there is a case to be made for the style you suggest, I don't see why we couldn't account for it.

**Comment by Drenmi** [comment] 2017-06-30 13:12
@Gawyn: I'm marking this as a duplicate of #2743. Please follow that issue for updates. I might take a stab at this over the weekend. 🙂

**Closed by Drenmi** 2017-06-30 13:12 UTC
Labels: duplicate
