### ISSUE TITLE
ORM specific suggestions

### ISSUE THREAD

**Issue by sivagollapalli** [bbatsov/rubocop#2290] opened 2015-10-02 10:48 UTC
Thanks for great gem. It helped a lot to follow the conventions and ruby standards. My project uses `mongoid` as a ORM. I have following snippet on project:

```
  Project.all.each do |p|
    # code here
  end
```
`rubocop` gave warning as Use `find_each` instead of `each`. As matter of fact there is no such method on `mongoid` to use. Could we avoid these if particular rails project uses `mongoid` as a ORM?

**Comment by palkan** [comment] 2015-10-08 07:51
Just turn the Rails/FindEach cop off within your config file:

```yaml
# .rubocop.yml
Rails/FindEach:
  Enabled: false
```

**Comment by sivagollapalli** [comment] 2015-10-12 11:32
@palkan As of now I have disabled in the same manner. But could we silent these kind of warnings without disabling the cop?

**Comment by palkan** [comment] 2015-10-12 12:35
What do you mean by "silent this kind of warnings"? What's wrong with disabling?

**Comment by maxjacobson** [comment] 2015-10-12 16:00
I think the issue is that inexperienced programmers might include RuboCop in their project and follow its advice blindly, and get some bad advice from RuboCop.

In theory, RuboCop could detect whether Mongoid is in use in a project and register offenses only when it is not. That's a bit complicated, but probably doable?

IMO, it could be resolved by explaining in the README/help documentation that if you're going to enable the Rails cops, be mindful that some of them are written with active record in mind.

**Comment by palkan** [comment] 2015-10-13 08:08
RuboCop doesn't consider project as a whole, only separate files. Thus, it doesn't know that you are using Mongoid.

I think that it possible to extend this cop's message with smth like: "Note: This cop only works with ActiveRecord. If you are using another ORM, you should disable it". @bbatsov

**Comment by bbatsov** [comment] 2015-10-13 08:45
Another approach would be to add a config option about the ORM, which some cops would take into account.

**Comment by sivagollapalli** [comment] 2015-10-16 05:49
@bbatsov +1

**Comment by alexdowad** [comment] 2015-12-31 08:54
> Another approach would be to add a config option about the ORM

I suggest that when `rubocop-rails` is split off into a separate gem, whoever maintains that gem can deal with this issue. If they want to add a new config param, fine. If they don't want to, fine.

**Comment by alexdowad** [comment] 2016-01-06 11:05
Maintainers, can we close this issue?

**Closed** 2016-01-06 11:33 UTC

**Comment by maxjacobson** [comment] 2016-02-11 19:32
@bbatsov @alexdowad I had an idea today that I want to share about these rails-specific issues that occur. Rather than splitting out `rails-rubocop`, split out

* `activesupport-rubocop`
* `activerecord-rubocop`
* `mongoid-rubocop` (optionally :smile:)

Doesn't it make sense?

Either way, I'm interested in helping with this process.

**Comment by bbatsov** [comment] 2016-02-12 08:20
Sounds reasonable. The only small problem is that if you're not assuming the presence of a Rails project you can't really guess which files to inspect with those cops, but I don't think the users would mind dealing with a bit of extra configuration. Or there can be some option to assume you're in a Rails project...
