### ISSUE TITLE
Robocop should accept YML strings as version instead of numbers.

### ISSUE THREAD

**Issue by chakrit** [bbatsov/rubocop#3055] opened 2016-04-18 05:13 UTC
Rubocop treats version specifier as a number which will cause problems in the future, for example, if we ever have a ruby `2.10` then there's no way to specify this and not have rubocop thinks it needs version `2.1` (which, of course, is a different version)

You can test this by specifying version `2.1000` and rubocop would load the parser for version `2.1`.

## Expected behavior

Rubocop should use version 2.2 if a YML string `'2.2'` is given.

## Actual behavior

Rubocop throw errors.

```
Error: Unknown Ruby version "2.2" found in `TargetRubyVersion` parameter (in /Users/chakrit/Documents/omise/omise-interfaces/.rubocop.yml).
Known versions: 1.9, 2.0, 2.1, 2.2, 2.3
```

## Steps to reproduce the problem

Use this `.rubocop.yml`:

```yml
---
inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: '2.2'
```

And just run `bundle exec rubocop`

## RuboCop version

```
$ rubocop -V
0.39.0
```

**Comment by alexdowad** [comment] 2016-05-31 18:47
If and when Ruby 2.10 is released (which will be never), we can change the way this works. For now, the current way is fine. Changing will not benefit anyone.

I suggest this issue can be closed.

**Comment by jonas054** [comment] 2016-06-02 20:05
And the issue is a duplicate of #2663. Closing.

**Closed by jonas054** 2016-06-02 20:05 UTC
