### ISSUE TITLE
Bug in Style/ExtraSpacing cop

### ISSUE THREAD

**Issue by mseppae** [bbatsov/rubocop#2127] opened 2015-08-10 06:13 UTC
File to test:
```ruby
class Foo
  def bar
    [ 0.8, 0, -0.002,  0.002,  0, 0.2, 0.02,-0.1,0.02,  0.5]
  end
end
```

Gives an error:
```
mseppae@Markos-MBP % rubocop -d foo.rb
An error occurred while Style/ExtraSpacing cop was inspecting foo.rb.
undefined method `[]' for 0.002:Float
```

Version information:
```
0.33.0 (using Parser 2.2.2.6, running on ruby 2.2.0 x86_64-darwin14)
```

**Comment by jonas054** [comment] 2015-08-10 13:59
Duplicate of #2113. Fixed on `master`.

**Closed by jonas054** 2015-08-10 13:59 UTC
Labels: duplicate
