### ISSUE TITLE
No longer starts up: "private method `load' called for Psych:Module"

### ISSUE THREAD

**Issue by dogweather** [bbatsov/rubocop#1510] opened 2014-12-18 04:17 UTC
I get this error when executing `rubocop` without options. I do get help output without crashing, for the `--help` option. I have no rubocop config file.

```
$ rubocop -V
0.28.0 (using Parser 2.2.0.pre.8, running on ruby 2.1.5 x86_64-darwin14.0)

$ rubocop 
private method `load' called for Psych:Module
/Users/robb/.rvm/gems/ruby-2.1.5/gems/rubocop-0.28.0/lib/rubocop/config_loader.rb:34:in `load_file'
/Users/robb/.rvm/gems/ruby-2.1.5/gems/rubocop-0.28.0/lib/rubocop/config_loader.rb:93:in `configuration_from_file'
/Users/robb/.rvm/gems/ruby-2.1.5/gems/rubocop-0.28.0/lib/rubocop/config_store.rb:40:in `for'
/Users/robb/.rvm/gems/ruby-2.1.5/gems/rubocop-0.28.0/lib/rubocop/target_finder.rb:111:in `excluded_dirs'
/Users/robb/.rvm/gems/ruby-2.1.5/gems/rubocop-0.28.0/lib/rubocop/target_finder.rb:90:in `find_files'
/Users/robb/.rvm/gems/ruby-2.1.5/gems/rubocop-0.28.0/lib/rubocop/target_finder.rb:60:in `target_files_in_dir'
/Users/robb/.rvm/gems/ruby-2.1.5/gems/rubocop-0.28.0/lib/rubocop/target_finder.rb:31:in `find'
/Users/robb/.rvm/gems/ruby-2.1.5/gems/rubocop-0.28.0/lib/rubocop/runner.rb:47:in `find_target_files'
/Users/robb/.rvm/gems/ruby-2.1.5/gems/rubocop-0.28.0/lib/rubocop/runner.rb:18:in `run'
/Users/robb/.rvm/gems/ruby-2.1.5/gems/rubocop-0.28.0/lib/rubocop/cli.rb:24:in `run'
/Users/robb/.rvm/gems/ruby-2.1.5/gems/rubocop-0.28.0/bin/rubocop:13:in `block in <top (required)>'
/Users/robb/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/Users/robb/.rvm/gems/ruby-2.1.5/gems/rubocop-0.28.0/bin/rubocop:12:in `<top (required)>'
/Users/robb/.rvm/gems/ruby-2.1.5/bin/rubocop:23:in `load'
/Users/robb/.rvm/gems/ruby-2.1.5/bin/rubocop:23:in `<main>'
/Users/robb/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/robb/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by rosswilson** [comment] 2015-01-11 17:11
Just to add, I'm getting this same error:

```
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.5-compliant syntax, but you are running 2.1.2.
private method `load' called for Psych:Module
/Users/wilsor31/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.28.0/lib/rubocop/config_loader.rb:34:in `load_file'
/Users/wilsor31/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.28.0/lib/rubocop/config_loader.rb:93:in `configuration_from_file'
/Users/wilsor31/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.28.0/lib/rubocop/config_store.rb:40:in `for'
/Users/wilsor31/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.28.0/lib/rubocop/target_finder.rb:111:in `excluded_dirs'
/Users/wilsor31/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.28.0/lib/rubocop/target_finder.rb:90:in `find_files'
/Users/wilsor31/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.28.0/lib/rubocop/target_finder.rb:60:in `target_files_in_dir'
/Users/wilsor31/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.28.0/lib/rubocop/target_finder.rb:31:in `find'
/Users/wilsor31/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.28.0/lib/rubocop/runner.rb:47:in `find_target_files'
/Users/wilsor31/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.28.0/lib/rubocop/runner.rb:18:in `run'
/Users/wilsor31/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.28.0/lib/rubocop/cli.rb:24:in `run'
/Users/wilsor31/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.28.0/bin/rubocop:13:in `block in <top (required)>'
/Users/wilsor31/.rbenv/versions/2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/Users/wilsor31/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.28.0/bin/rubocop:12:in `<top (required)>'
/Users/wilsor31/.rbenv/versions/2.1.2/bin/rubocop:23:in `load'
/Users/wilsor31/.rbenv/versions/2.1.2/bin/rubocop:23:in `<main>'
```

**Comment by bquorning** [comment] 2015-01-12 08:41
This sounds like an rbenv/rvm error. Could one of you please try this line:
```
ruby -e "require 'yaml'; puts Psych::VERSION; puts Psych.load('a: b')"
```

My output is
```
2.0.8
{"a"=>"b"}
```

**Comment by rosswilson** [comment] 2015-01-12 09:26
Unfortunately I tried upgrading to Ruby 2.2 (using rbenv) and reinstalling my Gem dependenies for my Rails app using bundler fixed the issue.

However, I can run the command under 2.2 and perhaps we can compare to one of the other guys who still have the issue:

```
2.0.8
{"a"=>"b"}
``` 

I will try downgrading back to Ruby 2.1.2 later today if that'll help.

**Comment by chetan** [comment] 2015-01-22 21:57
So I ran into this problem with another gem (`lolcommits`) under ruby 2.2 (was not able to repro under 2.1.x) and was able to create a simple test case after much debugging. It appears to be a problem with ruby as its fixed in ruby 2.2-head. 

https://github.com/chetan/psych_load_bug

**Comment by kofronpi** [comment] 2015-01-26 14:34
I have a problem with rubocop, this may be related: 

pak@*:~/***/**/*-*$ ruby -v
ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-linux]
pak@*:~/***/**/*-*$ rubocop -v
0.23.0
pak@*:~/***/**/*-*$ rvm use 2.1.5
Using /home/pak/.rvm/gems/ruby-2.1.5
pak@*:~/***/**/*-*$ rubocop -v
rubocop: command not found

**Comment by nofxx** [comment] 2015-02-01 01:21
Confirm bug with Psych > 2.0.8.
On another gem it only works if the "require 'yaml'" is on the same module where you use YAML.something.

**Comment by bbatsov** [comment] 2015-02-01 06:41
Obviously there's some problem, but I'm not sure how should we approach it.

**Comment by kdmcclin** [comment] 2015-02-10 15:16
Just in case this helps any other person googling this, I was getting this error when using Ruby 2.0 but when I changed to Ruby 2.1 it disappeared. *shrugs*

**Comment by xzo** [comment] 2015-03-02 21:25
I put `require 'yaml'` into `/usr/lib/ruby/2.2.0/rubygems.rb`

**Comment by xzo** [comment] 2015-03-19 12:54
Two installed psych gems causes this bug:
`/home/user/.gem/ruby/2.2.0/gems/psych-2.0.13`
`/usr/lib/ruby/2.2.0/psych.rb`

Solution:
`gem uninstall psych`

**Closed** 2015-04-05 07:14 UTC

**Comment by mame** [comment] 2015-05-16 16:13
FYI: this is [a rubygems bug](https://github.com/rubygems/rubygems/commit/5bb291fc31d16e527b4d0a1a4f64aa32f27f5255).  `gem update --system` will help you.

**Comment by brunowego** [comment] 2015-07-04 14:42
Thanks @mame! Works.

**Comment by h5tube** [comment] 2015-11-04 05:19
thanks , xzo.  this helps me.

**Comment by MaxPlank9** [comment] 2015-11-14 04:23
I have the same problem trying to use YAML. I stumbled on this page.

Ruby version "ruby 2.2.3p173"
Initially Psych 2.0.8 then I tried Psych 2.0.5 which didn't fix it. I confirmed the version of Psych ruby uses with 

ruby -e "require 'yaml'; puts Psych::VERSION"

To make sure the install of 2.0.5 worked and that 2.0.8 was initially present. I tried to use 2.0.15 but Ruby didn't pick it up.

**Comment by jesperronn** [comment] 2015-12-06 15:05
@bquorning and others. Thanks for sharing your troubleshooting tips. I ran into this with `scss-lint` today and solved it by:

* `gem uninstall psych`
* `gem install scss-lint`

Which was kind of strange, since I already was running most recent versions of psych (currently 2.0.15), sass (3.4.19), scss-lint (0.38.0).

Doing `gem install` to override was not enough... Had to uninstall psych to make it work :+1:
