### ISSUE TITLE
rubocop change and to && in some case will case unexpect error

### ISSUE THREAD

**Issue by EvanYu421** [bbatsov/rubocop#4710] opened 2017-09-07 06:54 UTC
## Original code

if params[:id]=="test" and groups.include? 16
   #do someting
end

## Expected behavior

if params[:id] == ("test") && groups.include? 16
   #do someting
end

## Actual behavior

if params[:id] == (test ") && groups.include? 16
   #do someting
end

there have missed a quotes

## Steps to reproduce the problem

not with special step.

only use rubocop -a

## RuboCop version

0.49.1 (using Parser 2.4.0.0, running on ruby 2.3.0 x86_64-darwin15)

**Comment by b-t-g** [comment] 2017-09-12 03:07
I have done a bit of digging and I found a few thing which may also be of interest

This code also reproduces the issue:
`foo =='test' and true`

It appears that it has to do with the lack of whitespace in between the "==" and the string itself.
On the one hand, correcting line 120 in and_or.rb
`corrector.insert_before(node.source_range, '(')`

to

`corrector.insert_before(node.source_range, '(') if whitespace_before_arg(node)`

Fixes the issue for this particular bug, it breaks other tests in the test suite, so there appears to be something deeper going on here.

**Comment by mikegee** [comment] 2017-09-12 11:42
I can't reproduce this on the latest `master` with `ruby 2.3.3p222 [x86_64-linux]`.

`foo =='test' and true` autocorrects to `(foo == 'test') && true`

```ruby
if params[:id]=="test" and groups.include? 16
#do someting
end
```
autocorrects to
```ruby
if (params[:id] == 'test') && groups.include?(16)
  # do someting
end
```

**Comment by b-t-g** [comment] 2017-09-12 13:06
@mikegee, indeed. I could have sworn I was using the most up to date version of master when I was investigating this yesterday, but upon fetching from upstream and merging it in again just now I can reproduce the results you got.

**Comment by Drenmi** [comment] 2017-09-12 15:22
Closing for now @b-t-g. If you manage to reproduce it, feel free to reopen. 🙂

**Closed by Drenmi** 2017-09-12 15:22 UTC
Labels: bug
