### ISSUE TITLE
Character encoding exception when writing the cache

### ISSUE THREAD

**Issue by jeremyf** [bbatsov/rubocop#2229] opened 2015-09-08 13:15 UTC
In `rubocop-0.34.0/lib/rubocop/result_cache.rb:34`

Given the following parameters:
```ruby
offenses = []
disabled_line_ranges = []
comments = [#<Parser::Source::Comment /path/to/project/Rakefile:1:1 "# Add your own tasks in files placed in lib/tasks ending in .rake,">,
 #<Parser::Source::Comment /path/to/project/Rakefile:2:1 "# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.">,
 #<Parser::Source::Comment /path/to/project/Rakefile:10:1 "# BEGIN `commitment:install` generator">,
 #<Parser::Source::Comment /path/to/project/Rakefile:11:1 "# This was added via commitment:install generator. You are free to change this.">,
 #<Parser::Source::Comment /path/to/project/Rakefile:16:5 "# 'commitment:jshint',">,
 #<Parser::Source::Comment /path/to/project/Rakefile:17:5 "# 'commitment:scss_lint',">,
 #<Parser::Source::Comment /path/to/project/Rakefile:24:1 "# END `commitment:install` generator">]
```

Rubocop throws a character encoding exception `"\xE4" from ASCII-8BIT to UTF-8`. The encoding of the [file](https://github.com/ndlib/cogitate/blob/master/Rakefile) is `UTF-8`, however the encoding of the parser comments is `ASCII-8BIT`.

**Comment by jonas054** [comment] 2015-09-08 14:12
Duplicate of #2213, fixed in #2221. So, fixed on `master` but not released as a gem version yet.

**Closed by jonas054** 2015-09-08 14:12 UTC
