### ISSUE TITLE
Style/MutableConstant autocorrect doesn't properly correct with `%w()` word list

### ISSUE THREAD

**Issue by bunnymatic** [bbatsov/rubocop#4074] opened 2017-02-25 03:15 UTC
Given class definition
```
# frozen_string_literal: true
class MyClass
  STRINGS=%w(a b c)
end
```

## Expected behavior

Run auto correct

```
# frozen_string_literal: true
class MyClass
  STRINGS=%w(a b c).freeze
end
```

## Actual behavior

Run auto correct

```
# frozen_string_literal: true
class MyClass
  STRINGS=[%w(a b c)].freeze
end
```

At this point STRINGS in the new (autocorrected) class is an array with an array.  Not the same as a flat array of strings.

## Steps to reproduce the problem

Save MyClass from the top as `my_class.rb`

Run
`rubocop -a my_class.rb`

check the diff

## RuboCop version

```
$ rubocop -V
0.47.1 (using Parser 2.4.0.0, running on ruby 2.3.3 x86_64-darwin15)
```

**Comment by pocke** [comment] 2017-02-25 08:08
I can't reproduce this problem. 


```sh
$ ls -a
.  ..  my_class.rb

$ cat my_class.rb
# frozen_string_literal: true
class MyClass
  STRINGS=%w(a b c)
end

$ rubocop -a my_class.rb
Inspecting 1 file
C

Offenses:

my_class.rb:2:1: C: [Corrected] Add a space after magic comments.
class MyClass
^
my_class.rb:3:10: C: [Corrected] Surrounding space missing for operator =.
  STRINGS=%w(a b c)
         ^
my_class.rb:3:11: C: [Corrected] Freeze mutable objects assigned to constants.
  STRINGS=%w(a b c)
          ^^^^^^^^^

1 file inspected, 3 offenses detected, 3 offenses corrected

$ cat my_class.rb
# frozen_string_literal: true

class MyClass
  STRINGS = %w(a b c).freeze
end

$ rubocop -V
0.47.1 (using Parser 2.4.0.0, running on ruby 2.4.0 x86_64-linux)
```

Do we need any configurations(`.rubocop.yml`) for reproduce?

**Comment by mikegee** [comment] 2017-02-25 13:50
This was fixed in https://github.com/bbatsov/rubocop/pull/3962, which isn't released yet.

**Comment by bunnymatic** [comment] 2017-02-25 19:19
Thanks.  I look forward to the release.

**Closed** 2017-03-03 06:09 UTC
