### ISSUE TITLE
Style/SingleSpaceBeforeFirstArg => SpacesBeforeFirstArg ?

### ISSUE THREAD

**Issue by lloeki** [bbatsov/rubocop#2510] opened 2015-12-17 11:04 UTC
`SingleSpaceBeforeFirstArg` checks what's written on the tin, but it's often customary, especially in DSLs, to have things like:

```ruby
    create_table :posts do |t|
      t.integer :author_id
      t.string  :title
      t.string  :body
      t.date    :published_at
      t.timestamps
    end
```

In which case the number of spaces is determined by alignment. IOW, obvious misalignment is a violation:

```ruby
    create_table :posts do |t|
      t.integer :author_id
      t.string    :title
      t.string  :body
      t.date  :published_at
      t.timestamps
    end
```

but this would still be valid:
```ruby
    create_table :posts do |t|
      t.integer :author_id
      t.string :title
      t.string :body
      t.date :published_at
      t.timestamps
    end
```

The latter is important to have regular, non-DSL code not fail all over the place.

`SingleSpaceBeforeFirstArg` thus becomes `SpacesBeforeFirstArg` with an `AllowAlignment` option defaulting to `false`.

**Comment by alexdowad** [comment] 2015-12-17 11:26
This is a duplicate of #2504.

**Closed** 2015-12-18 17:33 UTC
