### ISSUE TITLE
"x?? a : b" - Invalid character literal; use ?\s

### ISSUE THREAD

**Issue by mrbrdo** [bbatsov/rubocop#1878] opened 2015-05-08 18:11 UTC
The error message is wrong in this case, since it's valid syntax.
Not sure if community style guide specifies anything, but if it does it should show as a different error.

```ruby
def answer?
  true
end

answer?? 1 : 0
```

**Comment by bbatsov** [comment] 2015-05-08 19:34
@whitequark A parser bug maybe? RuboCop simply delegates to parser here.

**Comment by whitequark** [comment] 2015-05-08 19:42
Unable to reproduce.
```
$ ./bin/ruby-parse --22 -e $'def answer?\n  true\nend\nanswer?? 1 : 0'
(begin
  (def :answer?
    (args)
    (true))
  (if
    (send nil :answer?)
    (int 1)
    (int 0)))
```

**Comment by jonas054** [comment] 2015-05-08 19:49
@whitequark I think you need to run with `-w` to get the warning.

**Comment by whitequark** [comment] 2015-05-08 19:50
Oh. Reproduced.

**Comment by whitequark** [comment] 2015-05-08 20:04
Fixed in https://github.com/whitequark/parser/commit/a59e92c79773d15b230298481ae110e4de1fc5ed

**Comment by bbatsov** [comment] 2015-05-17 17:01
Thanks, @whitequark!

**Closed by bbatsov** 2015-05-17 17:01 UTC
