### ISSUE TITLE
Style/InverseMethods produces behaviourally different code

### ISSUE THREAD

**Issue by Valvyn** [bbatsov/rubocop#4643] opened 2017-08-02 07:46 UTC
## Expected behavior

Rubocop -a should produce code that has the same behaviour as the previous code.

This is the original code:

```ruby
x = y.reject { |key, _value| !(key =~ /c\d/) }
````
This is what a possible result could look like:

```ruby
x = y.select { |key, _value| key =~ /c\d/ }
````

## Actual behavior
Rubocop -a produces code that has different behaviour than the previous code.

The following code:

```ruby
x = y.reject { |key, _value| !(key =~ /c\d/) }
````

Results in this which does not have the same behaviour.

```ruby
x = y.reject { |key, _value| key =~ /c\d/ }
````

## Steps to reproduce the problem

run the following code with this rubocop command:

```
rubocop -a --only Style/InverseMethods
```

```ruby
x = y.reject { |key, _value| !(key =~ /c\d/) }
````

## RuboCop version
```
0.49.1 (using Parser 2.4.0.0, running on ruby 2.2.4 x86_64-linux)
```

**Comment by mikegee** [comment] 2017-08-02 14:57
I confirmed the incorrect behavior. It is important to note the _3_ corrections that occur here:

```
Offenses:

test/test.rb:1:5: C: [Corrected] Style/InverseMethods: Use reject instead of inverting select.
x = y.select { |key, _value| key !~ /c\d/ }
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test/test.rb:1:5: C: [Corrected] Style/InverseMethods: Use select instead of inverting reject.
x = y.reject { |key, _value| !(key =~ /c\d/) }
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test/test.rb:1:30: C: [Corrected] Style/InverseMethods: Use !~ instead of inverting =~.
x = y.reject { |key, _value| !(key =~ /c\d/) }
                             ^^^^^^^^^^^^^^^

1 file inspected, 3 offenses detected, 3 offenses corrected
```

**Comment by shevegen** [comment] 2017-08-02 19:06
It seems as if an additional check would be required since the situation is not as simple as a .select versus .reject, when combined with regexes, parens, and !. Other code examples out in the wild may behave correctly; I assume that this behaviour change is only possible in regex-styles like the above, right?

**Comment by rrosenblum** [comment] 2017-08-08 15:07
It looks like the issue here has to do with the body of the block being wrapped in a not. `x = y.reject { |key, _value| key !~ /c\d/ }` will properly corrects to `x = y.select { |key, _value| key =~ /c\d/ }`. I agree that this is a bug that should be fixed. I just added a test case for this. I will try to come up for a fix for this in the next couple of days.

**Closed** 2017-08-10 05:35 UTC
Labels: bug
