### ISSUE TITLE
Rubocop errors with ruby 2.4.0

### ISSUE THREAD

**Issue by msuhovec** [bbatsov/rubocop#4207] opened 2017-03-29 18:48 UTC
0.48.0 (using Parser 2.4.0.0, running on ruby 2.5.0 x86_64-darwin15)

4 errors occurred:
An error occurred while Rails/Blank cop was inspecting /Users/msuhovec/repos/sipity/app/forms/sipity/forms/work_submissions/etd/collaborator_form.rb:36:13.
An error occurred while Rails/Blank cop was inspecting /Users/msuhovec/repos/sipity/app/models/sipity/models/collaborator.rb:29:10.
An error occurred while Rails/Blank cop was inspecting /Users/msuhovec/repos/sipity/app/models/sipity/models/processing.rb:19:10.
An error occurred while Rails/Blank cop was inspecting /Users/msuhovec/repos/sipity/app/models/user.rb:33:4.

**Comment by andreaswachowski** [comment] 2017-03-29 19:25
There is not enough information in this issue report to fully analyze the cause, a (minimal) code example would be required so the error can be reproduced. Having said that, I suspect this problem has already been fixed on the master branch, see the PRs #4171 and #4179.

**Comment by bbatsov** [comment] 2017-03-30 07:37
This is fixed indeed.

**Closed** 2017-03-30 07:37 UTC
