### ISSUE TITLE
undefined method `call' for Array

### ISSUE THREAD

**Issue by stereodenis** [bbatsov/rubocop#2017] opened 2015-07-06 19:55 UTC
When I `require: rubocop-rspec` and try to use auto-correcting

https://github.com/nevir/rubocop-rspec/issues/41

```
bundle exec rubocop spec/models -a
Inspecting 47 files
....

4 files inspected, no offenses detected
undefined method `call' for #<Array:0x007f9603fcc740>
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/cop/corrector.rb:46:in `block in rewrite'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/cop/corrector.rb:45:in `each'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/cop/corrector.rb:45:in `rewrite'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/cop/team.rb:90:in `autocorrect_one_cop'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/cop/team.rb:65:in `autocorrect'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/cop/team.rb:35:in `inspect_file'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/runner.rb:135:in `inspect_file'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/runner.rb:106:in `block in do_inspection_loop'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/runner.rb:100:in `loop'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/runner.rb:100:in `do_inspection_loop'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/runner.rb:78:in `process_file'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/runner.rb:53:in `block in inspect_files'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/runner.rb:51:in `each'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/runner.rb:51:in `inspect_files'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/runner.rb:30:in `run'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/cli.rb:26:in `run'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/bin/rubocop:13:in `block in <top (required)>'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/bin/rubocop:12:in `<top (required)>'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/rubocop:23:in `load'
/Users/stereodenis/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/rubocop:23:in `<main>'
```

**Comment by ryanzbone** [comment] 2015-07-30 16:28
Me and @twyfordr are experiencing this as well

**Comment by Averethel** [comment] 2015-08-04 12:30
Happens to me as well

**Comment by pabloq** [comment] 2015-08-06 17:23
me too

**Comment by dlong266** [comment] 2015-08-13 14:28
Yep. Same here

**Comment by pabloq** [comment] 2015-08-13 15:08
I solved the problem putting the "require rubocop-rspec" at the top in the .rubocop.yml file.

require: rubocop-rspec
AllCops:
  RunRailsCops: true
....
...

**Comment by jgrau** [comment] 2015-08-19 12:05
Same issue here and @pabloq 's suggestion did not work for me.

**Comment by bbatsov** [comment] 2015-08-21 15:44
I don't see how this is caused by RuboCop. It seems to me `rubocop-rspec` is doing something it should not be doing.

**Comment by pabloq** [comment] 2015-08-21 15:56
yeah, you are rigth the problem reappear to be @jgrau and yes, I think that is related with rubocop-rspec.

I figure out that in my case is related with the auto_correct option and rubocop-rspec. I seems like the autocorrect doest work well with rubocop-rspec, it returns that everything is ok, but if I run without the auto_correct option, I see some detections not detected by the auto_correct.

I run
rake rubocop:auto_correct, everything pass and get the array error.

then,

rake rubocop, returns some errors related with rpsec.

**Comment by bquorning** [comment] 2015-08-25 02:56
The problem was in `RuboCop::Rspec` and has been fixed on their master branch: https://github.com/nevir/rubocop-rspec/commit/c2b3497a4d6fadec2bebd98e5d97325e83675661.

As I see it, this ticket can be closed.

**Closed** 2015-08-26 09:28 UTC
Labels: bug
