### ISSUE TITLE
Style/EmptyElse: outputing confusing ruby code

### ISSUE THREAD

**Issue by danlo** [bbatsov/rubocop#2855] opened 2016-02-16 17:12 UTC
Greetings,

I learned today, that an "if-clause" returns nil if it isn't true.  Ergo

```ruby
a = if false
   'def'
else 
   nil
end

a.nil? # = true
```

Style/EmptyElse converted the above to:

```ruby
a = 'abc'
a = if false
      'def'
    end

a.nil? # = true, would have thought this would have been 'abc'
```
However, I didn't know that effect of ruby.  I thought this was pretty awesome, but at the same time, a bit too _magical_ to be good coding.  

learned something new today! :)

**Comment by rrosenblum** [comment] 2016-02-17 19:41
Yes, some of Ruby's behavior when dealing with assignment and conditions can be weird. Another possibly unexpected behavior is if a variable is defined in a condition, even if the branch of the condition that assigns the variable is not reached, the variable will be defaulted to `nil`.

```ruby
[4] pry(main)> a
NameError: undefined local variable or method `a' for main:Object
[1] pry(main)> defined?(a)
=> nil
[2] pry(main)> if false
[2] pry(main)*   a = 1
[2] pry(main)* end  
=> nil
[3] pry(main)> a
=> nil
```

The confusing code happens with a combo of `Style/ConditionalAssignment` and `Style/EmptyElse`. In that specific case, I can see how the code can be confusing.

Do you have a suggestion for how something could work differently?

**Comment by danlo** [comment] 2016-02-19 15:43
I came up with 3 solutions

The code could output:

    Solution 1:

    # this is redudant, clear and magic free
    a = if condition
          'abc'
        else
          nil
        end

    Solution 2:

    # Put a comment in there, to indicate the behavior, good for a team of mixed skill levels
    a = if condition 
          'abc'
        end # #{var-name} is assigned nil if condition is false

    Solution 3:

    # Explain:
    # auto correct and output a comment informing the user of the above effect

Checking around, googling, I found the following

  https://github.com/bbatsov/rubocop/issues/1611      - most relevant
  https://github.com/bbatsov/rubocop/pull/1660/files  - passing interest
  https://github.com/bbatsov/rubocop/pull/1444        - passing interest

Looks like rubocop & team ran into this before.

**Comment by alexdowad** [comment] 2016-02-21 18:50
> However, I didn't know that effect of ruby.

Apparently you are a bit new to the language. There are a lot of other neat things you will learn as you go.

> I thought this was pretty awesome, but at the same time, a bit too magical to be good coding.

It's not magical at all. It's just straightforward Ruby code.

**Comment by rrosenblum** [comment] 2016-02-21 21:59
My recommendations to this would be to disable `Style/ConditionalAssignment`, disable `Style/EmptyElse`, change the configuration of `EmptyElse`, enable `Style/MissingElse`, leave the configuration as is, or wait for the new configuration for `ConditionalAssignment`.

Disabling `EmptyElse` will allow you to leave `nil` inside of `else`. 

Configuring `EmptyElse` to `empty`, which will only complain about empty `else` and not `nil` inside of `else`.

`MissingElse` will probably be more annoying because all `if` statements would require an `else` branch.

I am currently working on adding a configured style to `ConditionalAssignment` that will move the assignment to inside the condition instead of assigning to the condition.

I do not think that any of the maintainers would be interested in adding or maintaining a configuration that adds comments to the code. 

Enhancing the documentation of the cops is encouraged though.

**Comment by Drenmi** [comment] 2016-10-02 16:10
> Configuring EmptyElse to empty, which will only complain about empty else and not nil inside of else.

This is the solution, and it's already available. It doesn't seem like there's an actual issue here, so voting to close. 😀  @jonas054.

**Closed** 2016-10-02 20:20 UTC
