### ISSUE TITLE
Infinite loop when running the Style/SpecialGlobalVars cop

### ISSUE THREAD

**Issue by olbat** [bbatsov/rubocop#2502] opened 2015-12-15 15:48 UTC
Rubocop detects an infinite loop when running the `Style/SpecialGlobalVars` code with the `--auto-correct` option (rubocop version: `0.35.1`).

To reproduce:
```bash
$ echo 'p $/' | rubocop --auto-correct --only="Style/SpecialGlobalVars" --format=simple --stdin -
```
The backtrace:
```bash
== - ==
C:  1:  3: [Corrected] Prefer $INPUT_RECORD_SEPARATOR or $RS from the stdlib 'English' module over $/.

0 files inspected, 1 offense detected, 1 offense corrected

~/.gem/ruby/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:181:in `check_for_infinite_loop': Infinite loop detected in ~/core/-. (RuboCop::Runner::InfiniteCorrectionLoop)
	from ~/.gem/ruby/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:152:in `block in do_inspection_loop'
	from ~/.gem/ruby/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `loop'
	from ~/.gem/ruby/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `do_inspection_loop'
	from ~/.gem/ruby/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:93:in `process_file'
	from ~/.gem/ruby/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:58:in `block in inspect_files'
	from ~/.gem/ruby/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:56:in `each'
	from ~/.gem/ruby/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:56:in `inspect_files'
	from ~/.gem/ruby/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:34:in `run'
	from ~/.gem/ruby/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cli.rb:26:in `run'
	from ~/.gem/ruby/2.1.0/gems/rubocop-0.35.1/bin/rubocop:13:in `block in <top (required)>'
	from /usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
	from ~/.gem/ruby/2.1.0/gems/rubocop-0.35.1/bin/rubocop:12:in `<top (required)>'
	from ~/.gem/ruby/2.1.0/bin/rubocop:23:in `load'
	from ~/.gem/ruby/2.1.0/bin/rubocop:23:in `<main>'
```

**Comment by alexdowad** [comment] 2015-12-15 18:19
Please post the code which you are running RC on, or at least a small excerpt which can be used to reproduce the problem.

**Comment by mikegee** [comment] 2015-12-15 18:49
@alexdowad I ran the command given:

```bash
echo 'p $/' | rubocop --auto-correct --only="Style/SpecialGlobalVars" --format=simple --stdin -
```

and got the same error.

**Comment by alexdowad** [comment] 2015-12-15 18:55
@olbat @mikegee Sorry for the misunderstanding, and thank you. I'll have a look at this and see if I can fix it up.

**Comment by alexdowad** [comment] 2015-12-15 19:09
OK. The problem here is that "autocorrecting" code from stdin is a nonsensical thing to do.

After each round of autocorrections, RC writes the corrected code to the original source. So you know what it does in this case? ...It writes it out to a file called `-`. Pretty silly, huh?

RC should probably refuse to "autocorrect" code which comes from stdin. Other contributors, what do you think?

**Comment by rrosenblum** [comment] 2015-12-15 19:52
That sounds like a good idea to me. 

It might be a cool to have RC be able to correct code coming from `stdin`. Is there an easy way to have RC write to `stdout` instead of a file called `-`?

**Comment by alexdowad** [comment] 2015-12-15 19:53
The trouble is that stdout is normally used for the diagnostic output. Or is it written to stderr? I'm not sure.

**Comment by rrosenblum** [comment] 2015-12-15 20:01
I miss understood the initial issue. When I run 
```
echo 'p $/' | b rubocop --auto-correct --only="Style/SpecialGlobalVars" --format=simple --stdin -
```
The output is:
```
buffer: #<Parser::Source::Buffer:0x007fe1b50c3980>
== - ==
C:  1:  3: [Corrected] Prefer $INPUT_RECORD_SEPARATOR or $RS from the stdlib 'English' module over $/.

0 files inspected, 1 offense detected, 1 offense corrected
rubocop/lib/rubocop/runner.rb:181:in `check_for_infinite_loop': Infinite loop detected in rubocop/-. (RuboCop::Runner::InfiniteCorrectionLoop)
        from rubocop/runner.rb:152:in `block in do_inspection_loop'
        ...
```

I thought the issue was that RuboCop was running forever. In actuality, RuboCop is detecting that what it is doing will produce an infinite loop and aborting. I wonder how difficult it would be to isolate this situation from other infinite loops (not sure what causes other infinite loops), and finish running successfully instead of blowing up.

**Comment by alexdowad** [comment] 2015-12-15 20:29
The reason why it detects an "infinite loop" is because after it autocorrects the source and writes it to a file called `-`, it then reads it back from stdin again and compares that to the original source. Of course, it's the same. If it would read back what it had written out, it wouldn't throw an "infinite loop" error.

**Comment by jonas054** [comment] 2015-12-19 17:47
We should exit with an error message if both `--auto-correct` and `--stdin` are given (easy), or support it by doing the auto-corrections in memory rather that writing to file (hard).

**Comment by alexdowad** [comment] 2015-12-19 17:51
I'm doing the latter right now.

**Comment by alexdowad** [comment] 2015-12-19 17:51
(And it's not really hard, by the way. You'll see the PR in 15 minutes or so.)

**Comment by alexdowad** [comment] 2015-12-19 18:33
OK, just pushed a fix [here](https://github.com/bbatsov/rubocop/pull/2515).

What do you think of `====================` as a delimiter between the warning summary and autocorrected code? Can we do better? (I was hoping that the warning summary was sent to stderr, but it goes to stdout.)

**Closed** 2015-12-20 21:16 UTC

**Comment by olbat** [comment] 2015-12-29 13:43
Perfect, thank you for the quick fix ! :)

**Comment by eterps** [comment] 2016-10-07 08:41
@alexdowad the `=` based delimiter is fine, but it can't be disabled.
What if you want editor integration for autoformatting? In Vim for example rubocop would get the source on STDIN, and thanks to your fix it can now autocorrect to STDOUT, but the editor will then receive the delimiter and offense report.
For that to work we need to be able to disable the offense report (i.e. `cat foo.rb |rubocop --auto-correct --no-offense-report --stdin -` or something like that).
Your thoughts?

**Comment by alexdowad** [comment] 2016-10-07 14:12
@eterps, you are very right. I don't have any opinion on whether `--no-offense-report` is worth including in Rubocop or not. You can always create a custom Formatter instead. Or if you want to open a PR, please do so and see what @bbatsov will say about it.
