### ISSUE TITLE
Performance parsing multi-line strings

### ISSUE THREAD

**Issue by stripedpumpkin** [bbatsov/rubocop#4701] opened 2017-09-05 13:20 UTC
In some cases having rubocop lint a Rails app containing large multi-line strings can take a long time. On some VMs it can even stop responding for 10 min+. Of course I would not recommend anyone putting 20k+-characters strings in their ruby code, but I am mentioning it, in case something can be done to help the parser in these cases. Note I could not reproduce the issue perfectly, but the following minimal example should showcase what happens.

The problem is probably more consistently triggered with auto-correct enabled. 

```ruby
git checkout https://github.com/stripedpumpkin/rubocop_stressor.git
bundle
bundle exec rubocop -a
```

## RuboCop version

Reproduced in the two following settings:
```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-linux)
```
```
$ rubocop -V
0.44.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-linux)
```

**Comment by pocke** [comment] 2017-09-06 09:30
> Note I could not reproduce the issue perfectly, but the following minimal example should showcase what happens.

Maybe you can add `--cache false` command line option for reproduce.

-----



In my environment, it only takes  about18 seconds.


```bash
$ time rubocop --cache false -a
Inspecting 10 files
..........

10 files inspected, no offenses detected

total  18.80s
user   15.92s
system 2.87s
CPU    99%
cmd    rubocop --cache false -a
```


`Parser::Lexer::Literal#extend_string` is slow in my environment.

```bash
$ stackprof-run rubocop --cache false -a
Inspecting 10 files
..........

10 files inspected, no offenses detected

$ stackprof stackprof-out
==================================
  Mode: cpu(1000)
  Samples: 5423 (0.22% miss rate)
  GC: 1258 (23.20%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
      3435  (63.3%)        3435  (63.3%)     Parser::Lexer::Literal#extend_string
       258   (4.8%)         258   (4.8%)     Parser::Source::Buffer#slice
      3927  (72.4%)         139   (2.6%)     Parser::Lexer#advance
        37   (0.7%)          37   (0.7%)     Parser::Lexer::StackState#active?
        61   (1.1%)          31   (0.6%)     Parser::Lexer::Dedenter#dedent
        30   (0.6%)          30   (0.6%)     Parser::Lexer#literal
        27   (0.5%)          23   (0.4%)     Gem::StubSpecification#data
        20   (0.4%)          20   (0.4%)     Parser::Lexer::Literal#heredoc?
        54   (1.0%)          19   (0.4%)     Gem::BasicSpecification#have_file?
        49   (0.9%)          15   (0.3%)     Kernel#require
        44   (0.8%)          13   (0.2%)     Gem::StubSpecification#activated?
        67   (1.2%)          13   (0.2%)     Kernel#require
       210   (3.9%)          12   (0.2%)     Kernel#require
        31   (0.6%)          11   (0.2%)     Gem::StubSpecification#name
       106   (2.0%)          10   (0.2%)     Kernel#require
         9   (0.2%)           9   (0.2%)     RuboCop::Cop::Cop.badge
         5   (0.1%)           5   (0.1%)     RuboCop::Cop::Layout::TrailingBlankLines#investigate
         4   (0.1%)           4   (0.1%)     MonitorMixin#mon_enter
       172   (3.2%)           4   (0.1%)     Parser::Lexer#tok
         4   (0.1%)           4   (0.1%)     Parser::Lexer#version?
         4   (0.1%)           3   (0.1%)     Gem::Version#<=>
         3   (0.1%)           3   (0.1%)     RuboCop::Cop::AutocorrectLogic#autocorrect_requested?
         3   (0.1%)           3   (0.1%)     RuboCop::Cop::Layout::IndentHeredoc#indent_level
         8   (0.1%)           2   (0.0%)     RuboCop::NodePattern::Compiler#compile_expr
         2   (0.0%)           2   (0.0%)     Psych::ScalarScanner#tokenize
         2   (0.0%)           2   (0.0%)     block (2 levels) in <class:Ruby24>
         2   (0.0%)           2   (0.0%)     Parser::Source::Buffer#line_for_position
         2   (0.0%)           2   (0.0%)     RuboCop::Cop::Cop#file_name_matches_any?
         2   (0.0%)           2   (0.0%)     RuboCop::Cop::Cop#initialize
         2   (0.0%)           2   (0.0%)     Parser::Lexer#source_buffer=
```


Could you profiling it in your environment? 
You can use [stackprof](https://github.com/tmm1/stackprof) and [stackprof-run](https://github.com/pocke/stackprof-run) to profile.

**Comment by rrosenblum** [comment] 2017-09-13 14:41
[`memory_profiler`](https://github.com/SamSaffron/memory_profiler) is another good gem for identifying inefficient areas of code.

**Comment by Drenmi** [comment] 2017-09-17 12:13
@pocke: I assume this is fixed in your upstream PR? 🙂

**Comment by pocke** [comment] 2017-09-19 04:16
>  I assume this is fixed in your upstream PR? :slightly_smiling_face:

Maybe yes. I'll close this pull-request.

@stripedpumpkin If the problem is not still fixed in your environment, please reopen the issue.

**Closed by pocke** 2017-09-19 04:16 UTC
