### ISSUE TITLE
Bug in Lint/ShadowedException

### ISSUE THREAD

**Issue by ptarjan** [bbatsov/rubocop#3404] opened 2016-08-11 16:52 UTC
Why can't I have two errors on the same line?

---
## Expected behavior

No error
## Actual behavior

```
$ cat a.rb
begin
rescue TimeoutError, StandardError
  nil
end
$ ~/projects/rubocop/bin/rubocop a.rb
Inspecting 1 file
W

Offenses:

/tmp/a.rb:2:1: W: Do not shadow rescued Exceptions
rescue TimeoutError, StandardError
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```
## Steps to reproduce the problem

See above
## RuboCop version

```
$ ~/projects/rubocop/bin/rubocop -V
0.42.0 (using Parser 2.3.1.2, running on ruby 2.2.4 x86_64-darwin15)
```

**Comment by ptarjan** [comment] 2016-08-11 16:52
cc @rrosenblum

**Comment by mikegee** [comment] 2016-08-11 17:08
The message "Do not shadow rescued Exceptions" doesn't seem to agree, but I think the issue is that `TimeoutError` is redundant on that line.

**Comment by Drenmi** [comment] 2016-08-12 13:06
Looks like a duplicate of https://github.com/bbatsov/rubocop/issues/3283. (There was some discussion on how to improve the message.)

**Comment by rrosenblum** [comment] 2016-08-16 12:47
@Drenmi is correct, this is a duplicate of #3283. The messaging for this cop should be improved. I do not think that there has been a commit to improve the messaging yet.

**Comment by mikegee** [comment] 2017-01-24 16:24
I recommend closing this issue as a duplicate of #3283.

**Closed** 2017-01-24 16:27 UTC
