### ISSUE TITLE
Style/SafeNavigation has unexpected behavior

### ISSUE THREAD

**Issue by yosuke-oka** [bbatsov/rubocop#3642] opened 2016-10-18 04:41 UTC
when "foo is nil", these should return `true`
```ruby
foo.nil? || foo.bar
!foo || foo.bar
```

but, the copcode returns `nil`
```ruby
foo&.bar
```

below is the problem occurred in my project 

## Expected behavior

```ruby
# want to raise an error if "foo is nil" or "foo has errors".
raise RuntimeError if foo.nil? || foo.errors?
```

## Actual behavior

```ruby
# but through this condition when foo is nil.
raise RuntimeError if foo&.errors?
```

## RuboCop version

```
$ rubocop -V
0.43.0 (using Parser 2.3.1.4, running on ruby 2.3.0 x86_64-darwin15)
```

**Comment by tejasbubane** [comment] 2016-10-18 19:42
Duplicate of #3595. 

@yosuke-oka This has been fixed in the newer versions `0.44+`.

**Closed** 2016-10-19 02:00 UTC
