### ISSUE TITLE
Issue when running rubocop -a

### ISSUE THREAD

**Issue by askl56** [bbatsov/rubocop#2500] opened 2015-12-13 12:54 UTC
Hey all 

When running ```rubocop -a``` on a project with Ruby 2.2.1, it gets a quarter of the way through then I get this error:

``` 
undefined method `begin' for #<Parser::Source::Map::Variable:0x007f980436c858>
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cop/style/and_or.rb:113:in `correctable_send?'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cop/style/and_or.rb:95:in `correct_send'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cop/style/and_or.rb:67:in `block (2 levels) in correction'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cop/style/and_or.rb:65:in `each'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cop/style/and_or.rb:65:in `block in correction'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cop/corrector.rb:46:in `call'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cop/corrector.rb:46:in `block in rewrite'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cop/corrector.rb:45:in `each'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cop/corrector.rb:45:in `rewrite'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cop/team.rb:91:in `autocorrect_one_cop'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cop/team.rb:66:in `autocorrect'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cop/team.rb:36:in `inspect_file'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:190:in `inspect_file'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:157:in `block in do_inspection_loop'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `loop'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `do_inspection_loop'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:93:in `process_file'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:58:in `block in inspect_files'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:56:in `each'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:56:in `inspect_files'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:34:in `run'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cli.rb:26:in `run'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/bin/rubocop:13:in `block in <top (required)>'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/bin/rubocop:12:in `<top (required)>'
/usr/local/var/rbenv/versions/2.2.1/bin/rubocop:23:in `load'
/usr/local/var/rbenv/versions/2.2.1/bin/rubocop:23:in `<main>'
```

any ideas?

**Comment by jonas054** [comment] 2015-12-13 13:55
Duplicate of #2482. Fixed on `master`.

**Comment by askl56** [comment] 2015-12-13 13:56
So can be fixed with reinstall?

**Closed by jonas054** 2015-12-13 13:55 UTC

**Comment by alexdowad** [comment] 2015-12-13 15:58
> So can be fixed with reinstall?

It can be fixed by either waiting for the next release of RuboCop (and then upgrading), or cloning the RuboCop repository and running from your local repo, rather than using the gem.
