### ISSUE TITLE
Rubocop --auto-gen missing offenses when certain lines are too long.

### ISSUE THREAD

**Issue by bwinter** [bbatsov/rubocop#2913] opened 2016-03-04 22:27 UTC
## Expected behavior
I expect `rubocop --auto-gen` to create a `.rubocop_todo.yml` file that makes the next run of `rubocop` return no offending lines.
```sh
`--> rubocop --auto-gen; rubocop
Inspecting 2 files
CC

Offenses:

a.rb:1:81: C: Line is too long. [89/80]
# aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                                                                                ^^^^^^^^^
b.rb:4:1: C: Extra empty line detected at module body beginning.
b.rb:6:5: C: Use a guard clause instead of wrapping the code inside a conditional expression.
    if you =~ /get/ && that =~ /thing/
    ^^

2 files inspected, 3 offenses detected
Created .rubocop_todo.yml.
Run `rubocop --config .rubocop_todo.yml`, or add `inherit_from: .rubocop_todo.yml` in a .rubocop.yml file.
Inspecting 2 files
..

2 files inspected, no offenses detected
```

## Actual behavior
When I run `rubocop --auto-gen` and then `rubocop` alerts are thrown.
```sh
`--> rubocop --auto-gen; rubocop
Inspecting 2 files
CC

Offenses:

a.rb:1:81: C: Line is too long. [89/80]
# aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                                                                                ^^^^^^^^^
b.rb:4:1: C: Extra empty line detected at module body beginning.

2 files inspected, 2 offenses detected
Created .rubocop_todo.yml.
Run `rubocop --config .rubocop_todo.yml`, or add `inherit_from: .rubocop_todo.yml` in a .rubocop.yml file.
Inspecting 2 files
.C

Offenses:

b.rb:6:5: C: Use a guard clause instead of wrapping the code inside a conditional expression.
    if you =~ /get/ && that =~ /thing/
    ^^

2 files inspected, 1 offenses detected
```

## Steps to reproduce the problem
I haven't nailed it down any more than the following:

Create 2 files:

First file
```rb
# aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
(less than 88 chars and the bug won't show up, more than 88 it will)

Second file
```rb
# module
module Potamus

  def did
    if you =~ /get/ && that =~ /thing/
      return 'i sent you???????????????????????????????'

    else
      return 'gigi'

    end
  end
end
```
In this file the length of the line with all the `?`s matters. When I have 22 of them the error doesn't show up, when I have 23 of them it does (I suspect the actual character doesn't matter, and it's more related to line length and possibly where it is.)

Was also unable to get rubocop to execute it's analysis on the files in a reverse order so, it's not clear to me if that's important.

Hopefully this is simple enough to easily create the errors locally.

## RuboCop version

0.37.2
```sh
`--> rubocop -V
0.37.2 (using Parser 2.3.0.6, running on ruby 2.2.3 x86_64-linux)
```

**Comment by jonas054** [comment] 2016-03-12 09:21
Closing as duplicate of #2679.

**Closed by jonas054** 2016-03-12 09:21 UTC
