### ISSUE TITLE
Failure during Performance/Casecmp check

### ISSUE THREAD

**Issue by gmile** [bbatsov/rubocop#2754] opened 2016-02-01 11:48 UTC
Offence in question:
```
app/decorators/partner/product_params_decorator.rb:146:40: C: Performance/Casecmp: Use casecmp instead of downcase ==.
    obj['Fields'].find { |f| f['Name'].downcase == name.downcase }
                                       ^^^^^^^^^^^
```

Failure when running `rubocop --auto-correct --only Performance/Casecmp`:

```
undefined method `begin_pos' for nil:NilClass
/Users/gmile/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/rubocop-0.36.0/lib/rubocop/cop/performance/casecmp.rb:35:in `autocorrect'
```

Environment:

```
0.36.0 (using Parser 2.3.0.2, running on ruby 2.1.4 x86_64-darwin15.0)
```

Full stack trace: https://gist.github.com/gmile/7f1f22952657d4152926

**Comment by segiddins** [comment] 2016-02-01 14:23
This cop has seen a lot of changes since the last release. Can you see if the issue is fixed on master?

**Comment by alexdowad** [comment] 2016-02-05 07:02
Looks like it is fixed on master. Let's close.

**Closed** 2016-02-05 07:08 UTC
