### ISSUE TITLE
Do not place comments on the same line as the def keyword mishandling string interpolation

### ISSUE THREAD

**Issue by johnnyshields** [bbatsov/rubocop#4970] opened 2017-10-30 18:14 UTC
The hash in string interpolation is mistaken as a comment

```ruby
# CASE 1
app/helpers/application_helper.rb:278:57: C: Do not place comments on the same line as the def keyword.
  def options_menu_item(option, key, url = send("redraw_#{controller.controller_name}_path"))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# CASE 2
lib/fat_free_crm/permissions.rb:54:15: C: Do not place comments on the same line as the def keyword.
          def #{model}_ids
              ^^^^^^^^^^^^
```

**Comment by mikegee** [comment] 2017-10-30 23:40
duplicate of https://github.com/bbatsov/rubocop/issues/4886

**Closed** 2017-10-31 00:18 UTC
