### ISSUE TITLE
issue with Style/ExtraSpacing 

### ISSUE THREAD

**Issue by pironim** [bbatsov/rubocop#2118] opened 2015-08-07 15:23 UTC
I upgrade rubocop today and get this error when check for existing errors :

    rubocop --format progress --format offenses
Here is and error details:

    0.33.0 (using Parser 2.2.2.6, running on ruby 2.2.2 x86_64-linux)

and file content is

[parse_attributes_from_elasticsearch_spec.rb | uploaded via ZenHub](https://files.zenhub.io/55c4cd45dc54ddbd6184e35d)

here is stack trace `rubocop --debug`:

    An error occurred while Style/ExtraSpacing cop was inspecting /home/opensuse/code/sample.rb.
    undefined method `[]' for 12.1:Float
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-   0.33.0/lib/rubocop/cop/style/extra_spacing.rb:107:in `aligned_same_character?'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/style/extra_spacing.rb:82:in `block in aligned_with?'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/style/extra_spacing.rb:76:in `downto'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/style/extra_spacing.rb:76:in `each'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/style/extra_spacing.rb:76:in `aligned_with?'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/style/extra_spacing.rb:52:in `aligned_with_something?'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/style/extra_spacing.rb:28:in `block in investigate'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/style/extra_spacing.rb:24:in `each'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/style/extra_spacing.rb:24:in `each_cons'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/style/extra_spacing.rb:24:in `investigate'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/commissioner.rb:86:in `block (2 levels) in invoke_custom_processing'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/commissioner.rb:92:in `with_cop_error_handling'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/commissioner.rb:85:in `block in invoke_custom_processing'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/commissioner.rb:76:in `each'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/commissioner.rb:76:in `invoke_custom_processing'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/commissioner.rb:50:in `investigate'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cop/team.rb:33:in `inspect_file'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:135:in `inspect_file'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:106:in `block in do_inspection_loop'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:100:in `loop'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:100:in `do_inspection_loop'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:78:in `process_file'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:53:in `block in inspect_files'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:51:in `each'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:51:in `inspect_files'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/runner.rb:30:in `run'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/lib/rubocop/cli.rb:26:in `run'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/bin/rubocop:13:in `block in <top (required)>'
    /home/opensuse/.rvm/rubies/ruby-2.2.1/lib64/ruby/2.2.0/benchmark.rb:303:in `realtime'
    /home/opensuse/.rvm/gems/ruby-2.2.1/gems/rubocop-0.33.0/bin/rubocop:12:in `<top (required)>'
    /home/opensuse/.rvm/gems/ruby-2.2.1/bin/rubocop:23:in `load'
    /home/opensuse/.rvm/gems/ruby-2.2.1/bin/rubocop:23:in `<main>'
    /home/opensuse/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    /home/opensuse/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

this line raise error :
    https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/extra_spacing.rb#L107

text[0] not working for some reason

**Comment by jonas054** [comment] 2015-08-08 09:40
Duplicate of #2113.

**Closed by jonas054** 2015-08-08 09:40 UTC
Labels: duplicate
