### ISSUE TITLE
Specifying AllCops/Include overwrites AllCops/Include from default config

### ISSUE THREAD

**Issue by agross** [bbatsov/rubocop#2929] opened 2016-03-09 00:25 UTC
With an empty `.rubocop.yml`:
```
$ bundle exec rubocop -L -d
For somewhere/shell: configuration from somewhere/shell/.rubocop.yml
Default configuration from C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/config/default.yml
Inheriting configuration from C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/config/enabled.yml
Inheriting configuration from C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/config/disabled.yml
somegem.gemspec
Gemfile
Guardfile
Rakefile
Thorfile
bin/console
...
```

With this `.rubocop.yml`:
```
AllCops:
  Include:
    - '**/.simplecov'
```

```
$ bundle exec rubocop -L -d
For somewhere/shell: configuration from somewhere/shell/.rubocop.yml
Default configuration from C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/config/default.yml
Inheriting configuration from C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/config/enabled.yml
Inheriting configuration from C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/config/disabled.yml
.simplecov
bin/console
...
```

In the first example, the default `*file` patterns match files. Ass soon as I add new patterns with `AllCops/Include`, these patterns are disregarded.

I'm running 0.37.2.

**Comment by agross** [comment] 2016-03-09 14:38
I'm referring to this line from the readme:

> The Include and Exclude parameters are special. They are valid for the directory tree starting where they are defined. They are not shadowed by the setting of Include and Exclude in other .rubocop.yml files in subdirectories.

AllCops/Include in my local `.rubocop.yml` should not overwrite, rather extend, the defaults.

**Comment by jonas054** [comment] 2016-03-13 13:19
This is intended behavior. A configuration parameter that is an array *replaces* the value of the default parameter with the same name. The reason for this is that it would otherwise not be possible to remove elements from a default array through overriding.

The section you quote from the REAME talks about `.rubocop.yml` files in your project and how values are selected from them. It does not talk about the default configuration.

But I see that the README does not describe these details of overriding configuration. We should add something there.

**Comment by agross** [comment] 2016-03-13 23:38
Many thanks for the clarification, @jonas054!

**Comment by Drenmi** [comment] 2016-07-03 08:09
@jonas054: Documentation added in the manual, here: https://github.com/bbatsov/rubocop/commit/d40e8a9f800b8cac7345a67fab32139a2687273f#diff-04c6e90faac2675aa89e2176d2eec7d8L299

**Comment by jonas054** [comment] 2016-07-03 10:57
Thanks @Drenmi. As the description is already in [the manual](https://github.com/bbatsov/rubocop/blob/master/manual/configuration.md#inheritance), I'm closing the issue.

**Closed by jonas054** 2016-07-03 10:57 UTC
Labels: documentation
