### ISSUE TITLE
False positives in Style/StringReplacement

### ISSUE THREAD

**Issue by mneumark** [bbatsov/rubocop#2340] opened 2015-10-22 19:03 UTC
I noticed that if the pattern and replacement are both `String`s, and the pattern is multiple characters, but the replacement is a single character, you still get:
`Use 'tr' instead of 'gsub'`

So for example:
```ruby
[1] pry(main)> 'abcdef'.gsub('cde', '!')
=> "ab!f"
[2] pry(main)> 'abcdef'.tr('cde', '!')
=> "ab!!!f"
```

As you can see, the result is different, so rubocop should not be complaining about this.

**Comment by rrosenblum** [comment] 2015-10-23 01:08
@mneumark, what version of RuboCop are you using? I ran your example against `master` and no offense was produced.

```ruby
# test.rb
'abcdef'.gsub('cde', '!')
```
```
$ b rubocop --only Performance/StringReplacement --cache false test.rb   
Inspecting 1 file
.

1 file inspected, no offenses detected
```

**Comment by mneumark** [comment] 2015-10-23 01:34
Okay, I thought I was accurately replicating the situation but apparently not. I am using 0.34.2.

Here is a sample of the actual code:
```ruby
'foobarbaz'.gsub("\xe2\x80\x93", '-')
```

**Comment by rrosenblum** [comment] 2015-10-23 18:35
I have verified that this is a bug. I can reproduce this on my system. I am going to have to do some digging to figure out the best way to fix this. Even though the string appears to have more than one character, it is part of a unicode sequence to produce a single character. Ruby reports this as a string of length one.

**Comment by rrosenblum** [comment] 2015-10-25 03:20
I was working on a fix for this, but after playing around with the functionality of `gsub`, `tr`, and `delete` using unicode patterns and replacement, I no longer believe this is a bug. All of the methods treat unicode as a single character when matching and replacing.

```ruby
pry(main)> "xe2\xe2\x80\x93".gsub("\xe2\x80\x93", '(')
=> "xe2("
pry(main)> "xe2\xe2\x80\x93".tr("\xe2\x80\x93", '(')
=> "xe2("
pry(main)> "!!".gsub("!", "\xe2\x80\x93")
=> "––"
pry(main)> "!!".tr("!", "\xe2\x80\x93")
=> "––"
```

**Comment by alexdowad** [comment] 2015-12-11 21:30
Looks like this can be closed.

**Closed** 2015-12-11 21:57 UTC
