### ISSUE TITLE
Feature suggestion: Friendlier message when `inherit_from` file is not found

### ISSUE THREAD

**Issue by jaredbeck** [bbatsov/rubocop#4969] opened 2017-10-30 17:23 UTC
If approved, I will be happy to implement this and submit PR.

## Steps to reproduce the problem

`inherit_from: file_that_does_not_exist.yml`

## Suggested behavior

A friendly, concise error message.

```
bin/rubocop
File not found: file_that_does_not_exist.yml
# This error would be printed to stderr using Kernel.warn
echo $?
2
```

## Actual behavior

Crash and stack trace.

```
bin/rubocop
No such file or directory @ rb_sysopen - /herp/derp/file_that_does_not_exist.yml
/Users/jared/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/config_loader.rb:214:in `read'
.. snip many lines, you get the idea ..
/Users/jared/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/bin/rubocop:12:in `<top (required)>'
bin/rubocop:18:in `load'
bin/rubocop:18:in `<main>'
echo $?
2
```

## RuboCop version

Not relevant to feature suggestion.

**Comment by bquorning** [comment] 2017-10-30 18:31
This sounds like a good idea (depending on how simple/complex it would be to implement).

The error message should probably also say which in file (and line?) the `inherit_from` line was present.

**Comment by Drenmi** [comment] 2017-10-30 19:15
Duplicate of #3396.

**Closed by Drenmi** 2017-10-30 19:15 UTC

**Comment by jaredbeck** [comment] 2017-10-30 20:10
> Duplicate of #3396.

I agree that this is a duplicate. Thanks Ted. I'll continue the conversation over at #3396.

**Comment by Drenmi** [comment] 2017-10-30 20:38
PRs also welcome. 😊
