### ISSUE TITLE
Rubcop gives error on valid regex

### ISSUE THREAD

**Issue by pitosalas** [bbatsov/rubocop#4598] opened 2017-07-11 21:34 UTC
Here's my ruby:

```
str.nil? ? "" : str.gsub(/(\s+|\"|\“|\”)/, " ")
```
Which I believe is correct Ruby. 2.4.1 processes it without error. However Rubocop 0.49.1 gives this error:

```
invalid multibyte character: /(\s+|\"|\“|\”)/ (Using Ruby 2.4 parser; configure using TargetRubyVersion` parameter, under `AllCops`) (Syntax)
```

```
rubocop -v
0.49.1
```

**Comment by pocke** [comment] 2017-07-11 23:29
Minimum code to reproduce 

```ruby
/\”/

# `”` is an any multibyte character.
/\あ/
```


I guess it is a parser gem or MRI bug.
Parser raises an error at here. https://github.com/whitequark/parser/blob/ff3ec9eda591d2a1cb28e1b041f3a47aa3dfb919/lib/parser/builders/default.rb#L1568

And I can cause the error by `Regexp.new("\\あ")`.

**Comment by Drenmi** [comment] 2017-07-12 04:23
None of the quotation marks should need escaping, right, since they aren't regexp modifiers?

```ruby
str.nil? ? "" : str.gsub(/(\s+|"|“|”)/, " ")
```

**Comment by jonas054** [comment] 2017-10-09 08:27
Yes, those shouldn't be escaped, and removing the backslashes solves the problem. Closing.

**Closed by jonas054** 2017-10-09 08:27 UTC
Labels: bug
