### ISSUE TITLE
Offense Rails/FilePath for Rails.root misdetected

### ISSUE THREAD

**Issue by kirrmann** [bbatsov/rubocop#3974] opened 2017-01-26 19:37 UTC
Rubocop version: 0.47.1

For example the following command is listed as offense, but there is no path to join

`system "wheneverize '#{Rails.root}'" unless File.exist? @filepath`

if I use `rails_path = Rails.root` there is no offense detected, so there must be a problem with the curly brackets I guess.

**Comment by mikegee** [comment] 2017-01-26 20:55
This issue looks like a duplicate of https://github.com/bbatsov/rubocop/issues/3947.

**Comment by dabroz** [comment] 2017-02-09 21:44
I have another example of misdetection:

    Dir.glob(Rails.root.join("config/**/*.env.#{Rails.env}"), File::FNM_DOTMATCH))

**Comment by mikegee** [comment] 2017-02-10 13:20
@dabroz Rubocop wants you to rewrite that example as:

```ruby
Dir.glob(Rails.root.join('config', '**', "*.env.#{Rails.env}"), File::FNM_DOTMATCH))
```

I think the offense message needs changed somehow. [I was confused by it recently, too.](https://github.com/bbatsov/rubocop/issues/4002)

**Closed** 2018-01-14 20:40 UTC
