### ISSUE TITLE
Feature Request: Cop to force 2.1 style visibility modifiers

### ISSUE THREAD

**Issue by ptarjan** [bbatsov/rubocop#3041] opened 2016-04-13 20:33 UTC
We'd like `private` to be forced to appear before the method instead of just somewhere randomly in the file.

```
# bad
class Foo
  private

  def bar
  end

  def baz
  end
end
```

```
# good
class Foo
  private def bar
  end

  private def baz
  end
end
```

Autocorrecting all our existing code is pretty important for this cop.

**Comment by Drenmi** [comment] 2016-10-02 16:06
Looks like this might be a duplicate of #2687? @ptarjan, @jonas054.

**Comment by jonas054** [comment] 2016-10-03 07:36
Yes, it's a duplicate. Closing this one.

**Closed by jonas054** 2016-10-03 07:36 UTC
