### ISSUE TITLE
[BUG] undefined method `source' for nil:NilClass

### ISSUE THREAD

**Issue by kvokka** [bbatsov/rubocop#3169] opened 2016-05-26 22:14 UTC
Lay down on code
```
  def mean
    return if length == 0
  end
```

with trace

```
Inspecting 10 files
......

6 files inspected, no offenses detected
undefined method `source' for nil:NilClass
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/cop/style/zero_length_predicate.rb:65:in `replacement'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/cop/style/zero_length_predicate.rb:57:in `block in autocorrect'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/cop/corrector.rb:57:in `block (2 levels) in rewrite'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/parser-2.3.1.0/lib/parser/source/rewriter.rb:194:in `transaction'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/cop/corrector.rb:56:in `block in rewrite'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/cop/corrector.rb:54:in `each'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/cop/corrector.rb:54:in `rewrite'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/cop/team.rb:132:in `autocorrect_all_cops'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/cop/team.rb:105:in `autocorrect'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/cop/team.rb:60:in `inspect_file'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:205:in `inspect_file'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:175:in `block in do_inspection_loop'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:165:in `loop'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:165:in `do_inspection_loop'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:87:in `process_file'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:57:in `each'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:57:in `inspect_files'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:35:in `run'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/lib/rubocop/cli.rb:30:in `run'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/bin/rubocop:14:in `block in <top (required)>'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/kvokka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.40.0/bin/rubocop:13:in `<top (required)>'
/home/kvokka/.rbenv/versions/2.3.1/bin/rubocop:23:in `load'
/home/kvokka/.rbenv/versions/2.3.1/bin/rubocop:23:in `<main>'
```

and works with
```
    return if send(:length) == 0
```

**Comment by alexdowad** [comment] 2016-05-30 14:28
Can't dup, please show your RC version and how you are running RC.

**Comment by kvokka** [comment] 2016-05-30 14:37
rubocop version 0.40.0, running as `rubocop -a`

full snippet of code

```
# frozen_string_literal: true
module Enumerable
  def sum
    inject(0) { |accum, i| accum + i }
  end

  def mean
    # rubocop bug, other way it dies https://github.com/bbatsov/rubocop/issues/3169
    # return -1 if send(:length) == 0
    return -1 if length == 0
    sum / length.to_f
  end

  def sigma
    return -1 if length < 2
    m = mean
    sum = inject(0) { |accum, i| accum + (i - m)**2 }
    Math.sqrt(sum / (length - 1).to_f)
  end

  def median
    return -1 if send(:length) == 0
    middle = length / 2
    sorted = sort
    length.even? ? (sorted[middle] + sorted[middle - 1]) / 2 : sorted[middle]
  end
end
```

**Comment by alexdowad** [comment] 2016-05-30 17:57
Still can't dup. What version of Ruby do you have?

**Comment by kvokka** [comment] 2016-05-30 18:25
0.40.0 (using Parser 2.3.1.0, running on ruby 2.3.1 x86_64-linux)

**Comment by jonas054** [comment] 2016-05-30 18:26
Closing as duplicate of #3166.

**Closed by jonas054** 2016-05-30 18:26 UTC
